[package]
name = "pihole-switch"
version = "0.1.0"
authors = ["devmatteini <dev.matteini@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "phs"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde_json = "1.0.59"
structopt = "0.3.20"

[dev-dependencies]
serial_test = "0.5.0"
serde_json = "1.0.59"
url = "2.1.1"
assert_cmd = "1.0.1"
predicates = "1.0.5"
